### ISSUE TITLE
Create new release and push to supermarket

### ISSUE THREAD

**Issue by JCotton1123** [customink-webops/magic_shell#17]
Hi, per the metadata.rb file `1.0.1` looks to be the latest version however there is no release here in Github or in the Supermarket. Can you please create these? Thx

**Comment by joshoohaah** [comment]
agreed.  can we push an updated release into supermarket? or tag as such?

**Comment by pkang** [comment]
👍 Yes, please release a new version to supermarket!

**Comment by calumbrodie** [comment]
+1 This doesn't seem to have been done in a while
